# Generated by Django 3.0.3 on 2020-02-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(default='', editable=False, max_length=100)),
                ('last_name', models.CharField(default='', editable=False, max_length=100)),
                ('aadhar_no', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField(default=0, editable=False)),
                ('password', models.CharField(default='123', editable=False, max_length=100)),
                ('conf_password', models.CharField(default='123', editable=False, max_length=100)),
            ],
        ),
    ]
