# Generated by Django 3.0.3 on 2020-02-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20200226_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
